name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: test/SigStat.Common.Test

    steps:
    - uses: actions/checkout@v2
    - name: Get email
      run: echo "EMAIL=$(git --no-pager log --format='%ae' -n1)" >> $GITHUB_ENV
      shell: bash
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Testek Futtatasa
      run: dotnet test --no-build --verbosity normal
  
    
    - name: Uzenet Kuldese Hiba Eseten
      if:  failure() #&& github.event_name == 'pull_request'}}  
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Sikertelen Unit test
        body: A unit tesztek hibat talaltak A Pull-Request linkje -> https://github.com/${{github.repository}}/pulls/${{github.event.number}}
        to: $EMAIL
        from: SigStat
        
            

