name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/SigStat.Common.Test

    steps:
    - name: email
      run: |
        echo "Get author info"
        echo "vmi"
        echo "${{github.event.pusher.email}}"
        echo "vege"
